package ru.vsu.rogachev.entities.enums;

public enum UserState {
    BASIC_STATE,
    WAIT_FOR_HANDLE_STATE,
    WAIT_CONFIRMATION_CODE_STATE,
    WAIT_OPPONENT_HANDLE_STATE,
    WAIT_OPPONENT_CONNECTION_STATE,
    DURING_THE_GAME
}
